### ISSUE TITLE
build error starting canvas example

### ISSUE THREAD

**Issue by Dierk** [paf31/purescript-sdom#9]
```
$ pulp run
* Building project in /projects/git/purescript-sdom/examples/canvas
* Build successful.
/projects/git/purescript-sdom/examples/canvas/output/DOM.HTML/foreign.js:5
  return window;
  ^

ReferenceError: window is not defined
    at exports.window (/projects/git/purescript-sdom/examples/canvas/output/DOM.HTML/foreign.js:5:3)
    at /projects/git/purescript-sdom/examples/canvas/output/Control.Monad.Eff/foreign.js:12:16
    at /projects/git/purescript-sdom/examples/canvas/output/Control.Monad.Eff/foreign.js:12:16
    at /projects/git/purescript-sdom/examples/canvas/output/Control.Monad.Eff/foreign.js:12:20
    at Object.__do [as main] (/projects/git/purescript-sdom/examples/canvas/output/Main/index.js:76:199)
    at Object.<anonymous> (/private/var/folders/88/cz3jknpx4n52zb0wrnrqlyf00000gp/T/pulp-run11829-62143-1krespk.qsl4.js:1:79)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
* ERROR: Subcommand terminated with exit code 1

```

**Comment by paf31** [comment]
You need to use `npm run example`.
